animals = ["bear", "ruby", "peacock", "kangaroo", "whale", "platypus"]
puts animals [1]
puts animals [2]
puts animals [0]
puts animals [3]
puts animals [4]
puts animals [2]
puts animals [5]
puts animals [4]


food = ["bacon", "steak", "potato", "onion", "apple", "sammich"]

puts food [5]
puts food [0]
puts food [1]
puts food [4]
puts food [2]
puts food [3]
puts food [2]
puts food [1]
puts food [4]
